// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOjPmstYLYqcJjnFJebIRg12Jm4-RbUAY',
    appId: '1:566180111144:web:a2431bf4a52d76d5bc661d',
    messagingSenderId: '566180111144',
    projectId: 'pertemuan9-21110',
    authDomain: 'pertemuan9-21110.firebaseapp.com',
    storageBucket: 'pertemuan9-21110.appspot.com',
    measurementId: 'G-2WPXGW3DH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx7d12RtDQB2yqC0P9xQNxaSr52sKz4dQ',
    appId: '1:566180111144:android:bdbb521e0208b350bc661d',
    messagingSenderId: '566180111144',
    projectId: 'pertemuan9-21110',
    storageBucket: 'pertemuan9-21110.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPjBaYV6jHnIOjC77wVSlFcoMaccpMHvo',
    appId: '1:566180111144:ios:6c3490bb11a739aabc661d',
    messagingSenderId: '566180111144',
    projectId: 'pertemuan9-21110',
    storageBucket: 'pertemuan9-21110.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPjBaYV6jHnIOjC77wVSlFcoMaccpMHvo',
    appId: '1:566180111144:ios:6c3490bb11a739aabc661d',
    messagingSenderId: '566180111144',
    projectId: 'pertemuan9-21110',
    storageBucket: 'pertemuan9-21110.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOjPmstYLYqcJjnFJebIRg12Jm4-RbUAY',
    appId: '1:566180111144:web:d5c561b175bd6236bc661d',
    messagingSenderId: '566180111144',
    projectId: 'pertemuan9-21110',
    authDomain: 'pertemuan9-21110.firebaseapp.com',
    storageBucket: 'pertemuan9-21110.appspot.com',
    measurementId: 'G-1G59LZ5RZ8',
  );
}